env: # Environment variables to pass to all tasks
    CIRRUS_CLONE_DEPTH: 1 # No need to clone with the whole history
    CIRRUS_WORKING_DIR: "/tmp/ci" # Where to clone the aosp-builder repo

# store our secrets here
    my_og_token: "ENCRYPTED[9f9fca2a7d2cdadfe74b816f7b61956fd25764ac8676aeb071325cb0f5a1e6f9e6f01878c2032ec45f09770e60a26c3e]" # main id
    github_token: "ENCRYPTED[1927b211c49de2c675929ca7bf29234b1934c69ff7c88e12c7060916bbc3d65027d8a8e07fa8ac948fa842679bc3f6ab]" # alt id
    bot_api: "ENCRYPTED[e7d3de2df978887652f3f200bd3b349b1cc885340e46d5a6d7b8cc4d97b0fbaf2d4d11a5c5543fb3139b5b6ca570765a]"
    chat_id: "ENCRYPTED[e600a076c29cec0c40df926ff02ba4eb550edbd3711d5bdd5c9355ef9e9ef9e52c68de042ec7a877a1e280b3e87d323e]"
    v_core: "16"
    s_core: "16"
    ext: "-4.19" # extend rom_name to avoid cache conflicts
    du_key: 0
    git_cookies: 0
    REAL_REPO_OWNER: "ENCRYPTED[e93f856a9f6ace177928de44161bde9d50d8cb7f190a3996dc5c8ac4a2ca22398ca983ff74d098ad6d1af996ae2ab266]" # main id

# store information about git here
    gmail: ehteshammalik18998@gmail.com

task:
    name: xyziop
    timeout_in: 120m
    container:
      image: nexgang/ubuntu:latest
      cpu: 8
      memory: 32G
      stateful: true
      greedy: true
    down_background_script:
      - git clone -b main https://$REAL_REPO_OWNER:$my_og_token@github.com/projects-nexus/ci-script /tmp/cs
      - mv /tmp/cs/* /tmp/ci
      - bash down*
    symc_script:
      - bash sy*
    compile_script:
      - bash bu*
    upl_script:
      - bash upl*
